# fly.toml app configuration file generated for babynamesil on 2026-04-07T14:18:02+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'babynamesil'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpus = 1
